import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 1]],
               ndmin=3,
               dtype='i4')
arr= np.array([2,4,1])
print(arr)
print(np.__version__)
print(type(arr))
print("dimensions = ",arr.ndim)
print(arr.dtype)
print("shape = ", arr.shape)
arr1= np.array([4,5,6])
print("using concatenate = ",np.concatenate((arr, arr1)))
print("using stack = ", np.stack((arr, arr1), axis=1))
print("using hstack = ", np.hstack((arr, arr1)))
print("using vstack = ", np.vstack((arr, arr1)))
print("using dstack = ", np.dstack((arr, arr1)))
print("sorted array = ", np.sort(arr))
A = np.array([[1,0,0],[0,1,0],[0,0,1]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A = \n", A)
print("B = \n", B)
print("A.B = \n", A@B)
print("A.B = \n",np.matmul(A,B))

